[build]
  command = "cd frontend && npm run build"
  publish = "frontend/build"

# Secrets scanning configuration
[build.environment]
  SECRETS_SCAN_OMIT_PATHS = "frontend/env.example,.secrets,frontend/build"
  SECRETS_SCAN_OMIT_KEYS = "REACT_APP_NHOST_SUBDOMAIN,REACT_APP_NHOST_REGION,REACT_APP_OPENROUTER_API_KEY,REACT_APP_N8N_WEBHOOK_URL,REACT_APP_NHOST_AUTH_URL,REACT_APP_NHOST_GRAPHQL_URL"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
